version: '3.8'

services:
  # Frontend Service (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx)
    restart: always
    depends_on:
      - backend
    networks:
      - aml_network

  # Backend Service (Flask)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./ml/models:/app/ml/models # Mount models directory
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    restart: always
    depends_on:
      - neo4j
    networks:
      - aml_network

  # Neo4j Database Service
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"] # Include APOC plugins for extended functionality
    volumes:
      - neo4j_data:/data
    restart: always
    networks:
      - aml_network

# Define the network for services to communicate
networks:
  aml_network:
    driver: bridge

# Define a volume for persistent Neo4j data
volumes:
  neo4j_data:
